assets_path:  ~/Repositories/og_data/ig_assets # put either absolute path or relative to current directory
g_dataset_path: Repositories/ig_data
# Not valid paths
og_dataset_path: ~/Repositories/og_data/ig_dataset
threedfront_dataset_path: data/threedfront_dataset
cubicasa_dataset_path: data/cubicasa_dataset
key_path: data/omnigibson.key


# assets_path:  /og_assets # put either absolute path or relative to current directory
# g_dataset_path: Repositories/ig_data
# og_dataset_path: /ig_dataset
# threedfront_dataset_path: data/threedfront_dataset
# cubicasa_dataset_path: data/cubicasa_dataset
# key_path: data/omnigibson.key
