env:
  action_timestep: 0.01666              # (float): environment executes action per action_timestep second
  physics_timestep: 0.01666             # (float): physics timestep for physx
  device: null                          # (None or str): specifies the device to be used if running on the gpu with torch backend

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: Scene

robots: []

objects: []

task:
  type: DummyTask
