type: Fetch
obs_modalities:
  - scan
  - rgb
  - depth
scale: 1
self_collisions: true
action_normalize: false
action_type: continuous
grasping_mode: sticky
disable_grasp_handling: true
rigid_trunk: false
default_trunk_offset: 0.365
default_arm_pose: diagonal30
default_reset_mode: tuck
controller_config:
  base:
    name: DifferentialDriveController
  arm_0:
    name: JointController
    motor_type: position
    command_input_limits: null
    command_output_limits: null
    use_delta_commands: true
  gripper_0:
    name: JointController
    motor_type: position
    command_input_limits: [-1, 1]
    command_output_limits: null
    use_delta_commands: true
  camera:
    name: JointController
    use_delta_commands: false