type: Fetch
obs_modalities: 
  - scan
  - rgb
  - depth
scale: 1.0
self_collisions: true
action_normalize: false
action_type: continuous
grasping_mode: sticky
rigid_trunk: false
default_arm_pose: diagonal30
default_trunk_offset: 0.365
controller_config:
  base:
    name: DifferentialDriveController
  arm_0:
    name: JointController
    motor_type: position
    command_input_limits: null
    use_delta_commands: true
  gripper_0:
    name: JointController
    motor_type: position
    command_input_limits: [-1, 1]
    command_output_limits: null
    use_delta_commands: true
  camera:
    name: JointController
    use_delta_commands: false