env:
  action_frequency: 30                  # (int): environment executes action at the action_frequency rate
  physics_frequency: 120                # (int): physics frequency (1 / physics_timestep for physx)
  device: null                          # (None or str): specifies the device to be used if running on the gpu with torch backend
  automatic_reset: false                # (bool): whether to automatic reset after an episode finishes
  flatten_action_space: false           # (bool): whether to flatten the action space as a sinle 1D-array
  flatten_obs_space: false              # (bool): whether the observation space should be flattened when generated
  use_external_obs: false               # (bool): Whether to use external observations or not
  initial_pos_z_offset: 0.1
  external_sensors: null                # (None or list): If specified, list of sensor configurations for external sensors to add. Should specify sensor "type" and any additional kwargs to instantiate the sensor. Each entry should be the kwargs passed to @create_sensor, in addition to position, orientation

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: InteractiveTraversableScene
  scene_model: Rs_int
  trav_map_resolution: 0.1
  default_erosion_radius: 0.0
  trav_map_with_objects: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  load_object_categories: null
  not_load_object_categories: null
  load_room_types: null
  load_room_instances: null
  load_task_relevant_only: false
  seg_map_resolution: 0.1
  scene_source: OG
  include_robots: false

robots:
  - type: Tiago
    name: Tiago
    action_type: continuous
    action_normalize: true
    proprio_obs:
      - eef_left_pos
      - eef_left_quat
      - eef_right_pos
      - eef_right_quat
      - trunk_qpos
      - arm_left_qpos_sin
      - arm_left_qpos_cos
      - arm_right_qpos_sin
      - arm_right_qpos_cos
      - gripper_left_qpos
      - gripper_right_qpos
      - grasp_left
      - grasp_right
    reset_joint_pos: null
    base_name: null
    scale: 1.0
    self_collision: true
    grasping_mode: physical
    rigid_trunk: false
    default_trunk_offset: 0.365
    default_arm_pose: vertical
    sensor_config:
      VisionSensor:
        sensor_kwargs:
          image_height: 512
          image_width: 512
      ScanSensor:
          sensor_kwargs:
            min_range: 512
            max_range: 512
    controller_config:
      base:
        name: JointController
      arm_left:
        name: InverseKinematicsController
      arm_right:
        name: InverseKinematicsController
      gripper_left:
        name: MultiFingerGripperController
      gripper_right:
        name: MultiFingerGripperController
      camera:
        name: JointController

objects: []

task:
  type: DummyTask

scene_graph:
  egocentric: true
  full_obs: true
  only_true: true
  merge_parallel_edges: false
