name: build-push-containers

on:
  release:
    types: [published]
  push:
    branches:
      - 'main'
      - 'og-develop'
      - 'action-primitives'

jobs:
  docker:
    runs-on: [self-hosted, linux, gpu]
    strategy:
      matrix:
        include:
          - dockerfile: docker/dev.Dockerfile
            image: ghcr.io/stanfordvl/omnigibson-dev
          - dockerfile: docker/prod.Dockerfile
            image: ghcr.io/stanfordvl/omnigibson
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to NVCR
        uses: docker/login-action@v2
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_PASSWORD }}   
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      -
        name: Build and push prod image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.dockerfile }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
